config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :infos do
  	member do
  		put "like",    to: "infos#upvote"
  	end
  end

  root "infos#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  belongs_to :info
end

app/models/info.rb
class Info < ActiveRecord::Base
  acts_as_votable
  has_many :categories
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :infos
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
	before_action :find_info, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@infos = Info.all.order("created_at DESC")
	end

	def show
	end

	def new
		@info = current_user.infos.build
	end

	def create
		@info = current_user.infos.build(info_params)

		if @info.save
			redirect_to @info, notice: "Info was successfully created"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @info.update(info_params)
			redirect_to @info, notice: "Info was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@info.destroy
		redirect_to root_path
	end

	def upvote
		@info.upvote_by current_user
		redirect_to :back
	end

	private

	def info_params
		params.require(:info).permit(:title, :description, :image, :category, :url)
	end

	def find_info
		@info = Info.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= simple_form_for @info, html: { multipart: true } do |f| %>
  <% if @info.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@info.errors.count, "error") %>
        prevented this Pin from saving
      </h2>
      <ul>
        <% @info.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :image, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :url, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt:"Choose a Category"} %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/infos/edit.html.erb
<div class="col-md-8 col-md-offset-2" id="edit_page">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Your Info</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center">Current Image</strong>
          <%= image_tag @info.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/infos/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>World News</h1>
    <!-- <p>Politics & Business News.</p>
    <p>A place where anyone can post informations from other sources</p>
    <p>Be the informant. I am going to have it for every continent. US, Africa, Europe, etc...</p>
    <p>Inform us about anything. It could be news, issues, health, corruption, anything.</p>
    <p>Inform the world</p>
    <p>A platform for new editors, anyone who wants to write about any issues or report some news.</p>
    <p>Some people could also take this platform and talk about their own stories and let people weight on it. For example: I can talk about my addiction with alcohol or talk about politics, business, environment</p>
    <p>weight on something that you dearly care about in the world.</p> -->
  </div>
</div>

<div class="transitions-enabled" id="infos">
  <% @infos.each do |info| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag info.url), info %>
      <h2>
        <%= link_to info.title, info %>
      </h2>
      <p class="small">
        <b class="s">SYNOPSIS</b>:
        <%= info.description %>
      </p>
      <p class="user">
        Source:
        <%= info.user.email %>
      </p>
    </div>
  <% end %>
</div>

app/views/infos/new.html.erb
<div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Info</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/infos/show.html.erb
<div class="row" id="info_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading info_image">
        <%= image_tag @info.url %>
      </div>
      <div class="panel-body">
        <h2>
          <%= @info.title %>
        </h2>
        <p class="description">
          <%= link_to "Read more...", @info.description %>
        </p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">
              Source:
              <%= @info.user.email %>
            </p>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_info_path(@info), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-heart"></span>
                <%= @info.get_upvotes.size %>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_info_path, class: "btn btn-default" %>
                <%= link_to "Delete", info_path, method: :delete, data: { confirm: "The informant are you sure?" }, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Informant</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "The Informant US", root_path %>
      </div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "New Info", new_info_path %>
          </li>
          <li>
            <%= link_to "Account", edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>
  <footer>
  <section>
    <h3><b>The Informant</b></h3>
    <p><b>Our Phone # is 000 - 000 - 0000</b><br>
    <p class="">The International Politics and Business News</P>
    </p>
  </section>
  <section>
    <h3>Connecter with Us</h3>
    <ul class="social">
      <li><a href="#"><img src="http://www.w3newbie.com/wp-content/uploads/facebook1.png" alt="" /></a></li>
      <li><a href="#"><img src="http://www.w3newbie.com/wp-content/uploads/googleplus.png" alt="" /></a></li>
      <li><a href="#"><img src="http://www.w3newbie.com/wp-content/uploads/twitter1.png" alt="" /></a></li>
      <li><a href="#"><img src="http://www.w3newbie.com/wp-content/uploads/youtube1.png" alt="" /></a></li>
    </ul>
    <p>&copy 2016 - The Informant. All rights reserved.</p>
    <p></p>
  </section>
</footer>
</body>
</html>